YaEm/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
]

urlpatterns += i18n_patterns(
    path("", include("main.urls", namespace="main")),
    path("", include("partner.urls", namespace="partner")),
    path("", include("cart.urls", namespace="cart")),
    path("", include("banquets.urls", namespace="banquets")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', include('registration.urls', namespace='register')),
    prefix_default_language=False,
)

handler404 = "YaEm.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Yaem/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from Yaem.views import robots_txt_view, sitemap_xml_view

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
    # robots txt
    path('robots.txt', robots_txt_view, name='robots_txt'),
    # sitemap xml
    path('sitemap.xml', sitemap_xml_view, name='sitemap_xml'),
    # api v1
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    # Online documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/v1/ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]


urlpatterns += i18n_patterns(
    # menu
    path("", include("main.urls", namespace="main")),
    # partner
    path("", include("partner.urls", namespace="partner")),
    # cart
    path("", include("cart.urls", namespace="cart")),
    # banquets
    path("", include("banquets.urls", namespace="banquets")),
    # users
    path('user/', include('users.urls', namespace='users')),
    prefix_default_language=False,
)

handler404 = "Yaem.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    # cart page
    path(
        '<slug:establishment_url_name>/cart', views.CartPage.as_view(), name='cart_page'
    ),
    # add to cart
    path('add/', views.add_to_cart, name='add'),
    # remove from cart
    path('remove/', views.remove_from_cart, name='remove'),
    # clear cart
    path('clear/', views.cart_remove, name='clear'),
]

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import DeliveryList, Main, Menu, set_language
from Yaem.settings import CACHES_LIFE_TIME

app_name = "main"

urlpatterns = [
    path(
        "<str:url_name>/menu",
        cache_page(CACHES_LIFE_TIME)(Menu.as_view()),
        name="menu_page",
    ),
    path("", cache_page(CACHES_LIFE_TIME)(Main.as_view()), name="main_page"),
    path("delivery/city/<slug:city_slug>/", DeliveryList.as_view(), name="city_filter"),
    path("set_language/<str:language>", set_language, name="set_language"),
    path(
        "delivery/",
        cache_page(CACHES_LIFE_TIME)(DeliveryList.as_view()),
        name="delivery_list_page",
    ),
]

cart/models/cart.py
import math

from django.contrib.auth import get_user_model
from django.contrib.auth.signals import user_logged_out
from django.contrib.sessions.models import Session
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from main.models import Dish


class Cart(models.Model):
    user = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        null=True,
    )
    items = models.ManyToManyField(
        to=Dish, through='CartItems', verbose_name='Блюда в корзине'
    )
    session_key = models.CharField(
        max_length=32, null=True, blank=True, verbose_name='Сессионный ключ'
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания корзины'
    )

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def total_cost(self):
        return sum(item.subtotal() for item in self.cart_items.all())

    def total_cost_with_service(self):
        return math.ceil(
            sum(item.subtotal_with_service() for item in self.cart_items.all())
        )

    def __str__(self):
        return f'{self.user}'


class CartItems(models.Model):
    cart = models.ForeignKey(
        to=Cart,
        on_delete=models.CASCADE,
        verbose_name='Корзина',
        related_name='cart_items',
    )
    dish = models.ForeignKey(to=Dish, on_delete=models.CASCADE, verbose_name='Блюдо')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')

    class Meta:
        verbose_name = 'Элемент корзины'
        verbose_name_plural = 'Элементы корзины'

    def subtotal(self):
        return self.dish.total_price() * self.quantity

    def subtotal_with_service(self):
        return self.dish.total_price_with_service() * self.quantity

    def __str__(self):
        return f'{self.dish} ({self.quantity}) в корзине'

cart/views/add_to_cart.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from cart.models import Cart, CartItems
from main.models import Dish


@csrf_exempt
def add_to_cart(request):
    # Получаем id блюда из POST-запроса
    dish_id = request.POST.get('dish_id')
    # Получаем объект блюда по его id или возвращаем ошибку 404, если блюдо не найдено
    dish = get_object_or_404(Dish, pk=dish_id)
    # Получаем пользователя, отправившего запрос
    user = request.user

    # Если пользователь аутентифицирован
    if request.user.is_authenticated:
        # Получаем или создаем корзину пользователя
        cart, created = Cart.objects.get_or_create(user=user)
    else:
        # Если пользователь не аутентифицирован, используем его сессионный ключ для создания или получения корзины
        session_key = request.session.session_key

        # Если сессионного ключа нет, сохраняем его
        if not session_key:
            request.session.save()
            session_key = request.session.session_key

        # Получаем или создаем корзину для анонимного пользователя
        cart, created = Cart.objects.get_or_create(
            session_key=session_key, user_id=None
        )

    # Получаем или создаем элемент корзины для данного блюда в корзине пользователя
    cart_item, item_created = CartItems.objects.get_or_create(cart=cart, dish=dish)

    # Увеличиваем количество выбранного блюда на 1 или устанавливаем его равным 1, если элемент корзины был только что создан
    if item_created:
        cart_item.quantity = 1
    else:
        cart_item.quantity += 1

    # Получаем количество выбранного блюда в корзине
    quantity_in_cart = cart_item.quantity
    cart_item.save()

    # Получаем промежуточную стоимость выбранного блюда
    subtotal = cart_item.subtotal()
    # Получаем общую стоимость всех блюд в корзине
    total = cart.total_cost()
    total_with_service = cart.total_cost_with_service()

    # Возвращаем JSON-ответ с информацией о добавленном блюде в корзину
    return JsonResponse(
        {
            'success': True,
            'subtotal': subtotal,
            'total': total,
            'total_with_service': total_with_service,
            'quantity': quantity_in_cart,
        }
    )

cart/views/cart_page.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView

from main.models import Client


class CartPage(TemplateView):
    template_name = 'cart/cart.html'

    def get(self, request, establishment_url_name=None, *args, **kwargs):
        client = get_object_or_404(Client, url_name=establishment_url_name)
        return render(
            request=request,
            template_name=self.template_name,
            context={
                'establishment_url': establishment_url_name,
                'service_percent': client.service,
                'delivery': client.delivery,
                'outside': client.outside,
                'phone': client.phone,
                'delivery_description': client.delivery_description,
            },
        )

cart/views/clear_cart.py
from django.contrib import messages
from django.shortcuts import redirect

from cart.models import Cart, CartItems


def cart_remove(request):
    # Если пользователь аутентифицирован
    if request.user.is_authenticated:
        # Получаем корзину пользователя
        user_cart = Cart.objects.filter(user=request.user).first()
        # Если у пользователя есть корзина
        if user_cart:
            # Удаляем все элементы корзины
            user_cart.cart_items.all().delete()
    else:
        # Получаем сессионный ключ пользователя
        session_key = request.session.session_key
        # Если сессионный ключ существует
        if session_key:
            # Получаем корзину анонимного пользователя
            user_cart = Cart.objects.filter(session_key=session_key).first()
            # Если у пользователя есть корзина
            if user_cart:
                # Удаляем все элементы корзины
                user_cart.cart_items.all().delete()

    messages.warning(request, message='Корзина очищена.')
    # Перенаправляем пользователя на предыдущую страницу
    return redirect(request.META.get('HTTP_REFERER'))

cart/views/remove_from_cart.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from cart.models import Cart, CartItems


@csrf_exempt
def remove_from_cart(request):
    # Получаем id блюда из POST-запроса
    dish_id = request.POST.get('dish_id')

    # Если пользователь аутентифицирован
    if request.user.is_authenticated:
        # Получаем корзину пользователя
        cart = Cart.objects.filter(user=request.user).first()
    else:
        # Получаем сессионный ключ пользователя
        session_key = request.session.session_key

        # Если сессионного ключа нет, сохраняем его
        if not session_key:
            request.session.save()
            session_key = request.session.session_key

        # Получаем корзину анонимного пользователя
        cart = Cart.objects.filter(session_key=session_key).first()

    # Если корзина пользователя существует
    if cart:
        # Получаем элемент корзины для данного блюда в корзине пользователя
        cart_item = get_object_or_404(CartItems, cart=cart, dish_id=dish_id)

        # Если количество выбранного блюда больше 1, уменьшаем его на 1
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            quantity_in_cart = cart_item.quantity
            cart_item.save()
        # Иначе удаляем элемент корзины
        else:
            cart_item.delete()
            quantity_in_cart = 0

        # Получаем промежуточную стоимость выбранного блюда (если элемент корзины существует) или устанавливаем равной 0
        subtotal = cart_item.subtotal() if cart_item else 0
        # Получаем общую стоимость всех блюд в корзине (если корзина существует) или устанавливаем равной 0
        total = cart.total_cost() if cart else 0
        total_with_service = cart.total_cost_with_service()

        # Возвращаем JSON-ответ с информацией о удалении блюда из корзины
        return JsonResponse(
            {
                'success': True,
                'subtotal': subtotal,
                'total': total,
                'total_with_service': total_with_service,
                'quantity': quantity_in_cart,
            }
        )

cart/templates/cart/cart.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block title %} {% translate 'Корзина' %} {{ total_price|intcomma }} ₸ {% endblock title %}

{% block content %}
<!--CART-->
<section class="skrollable pb-5"
         style="background-image: linear-gradient(0deg, rgba(51, 51, 51, 0.9), rgba(51, 51, 51, 0.9)), url({% static 'images/cart/4-min.jpg' %});
                     background-attachment: fixed; background-position: 70%; background-size: cover; background-repeat: no-repeat; min-height: 88vh">

    <!-- PART 1  -->
    <div class="container">
        <div class="row pt-5">

            {# Сообщения!!! #}
            {% include "main/included/messages.html" %}

            <div class="col-12">

                <a href="{% url 'main:menu_page' url_name=establishment_url %}">
                    <button data-aos="fade-right" class="btn btn-sm btn-animate shadow-0"
                            style="border-radius: 20px; " data-mdb-ripple-color="#fd7014">
                        <i class="fas fa-arrow-left-long fa-3x" style="color: #FD7014"> </i>
                    </button>
                </a>


                <h2 class="text-center">{% translate 'Корзина' %}</h2>
            </div>
        </div>
    </div>

    <!--  PART 2 CART LOGIC  -->
    {% load cart_tag %}
    {% user_cart request establishment_url as cart %}
    {% if cart.cart_items.all %}
    <div class="container my-3 position-relative" style="background: rgba(25, 25, 25, 0.5)">
        {% for item in cart.cart_items.all %}
        <!--        {# Обращаемся по классу и передаем id конкретно этой карточки(именно этого блюда) в js #}-->
        <div class="row shadow-5 cart-element"
             data-dish-id="{{ item.dish.id }}">

            <div class="col-6 my-auto me-0 pe-0">
                <p class="fs-6 fw-bold my-2 " style="line-height: 19px;">{{ item.dish.name }}</p>
                <p class="" style="font-size: 16px;
    line-height: 19px;
    color: inherit;
    margin-bottom: 8px;
    opacity: .6;">{{ item.dish.description }}</p>
            </div>
            <div class="col-3 mx-0 px-0 my-auto text-center">

                <!--                {# Обращаемся по классу и передаем id, href конкретно этой кнопки(именно этого блюда) в js #}-->
                <a class="btn btn-animate px-0 py-0 me-1 remove-from-cart"
                   data-mdb-ripple-color="danger"
                   data-mdb-ripple-radius="10"
                   href="{% url 'cart:remove' %}"
                   data-dish-id="{{ item.dish.id }}">
                    <i class="fas fa-circle-minus fa-2x text-danger"></i>
                </a>

                <!--                {# Обращаемся по классу и отрисовываем данные с бекенда #}-->
                <span class="my-auto cart-quantity"
                      data-dish-id="{{ item.dish.id }}">{{ item.quantity }}</span>


                <!--                {# Обращаемся по классу и передаем id, href конкретно этой кнопки(именно этого блюда) в js #}-->
                <a class="btn btn-animate px-0 py-0 ms-1 add-to-cart"
                   data-mdb-ripple-color="success"
                   data-mdb-ripple-radius="10"
                   href="{% url 'cart:add' %}"
                   data-dish-id="{{ item.dish.id }}">
                    <i class="fas fa-circle-plus fa-2x text-success"></i>
                </a>

            </div>

            <!--            {# Обращаемся по классу cart-subtotal-value и отрисовываем данные с бекенда #}-->
            <!--            {# передаем id конкретно этого элемента (именно этого блюда) в js #}-->
            <div class="col-3 my-auto text-center">
                <h6 class="cart-subtotal-value"
                    data-dish-id="{{ item.dish.id }}">
                    {{ item.subtotal|intcomma }} ₸
                </h6>
            </div>
            <hr class="my-1">
        </div>


        {% endfor %}
        <div class="d-flex">
            <!--            {# Обращаемся по классу cart-total-value и отрисовываем данные с бекенда #}-->
            {% if service_percent > 0 %}
            <div class="col-9 text-end mx-0 px-0">
                <p class="mt-3 mb-0">{% translate 'Подитог: ' %}
                </p>
                <p class="my-0">{% translate 'Обслуживание: ' %} </p>
                <p class="my-0 fw-bold fs-5"> {% translate 'Итого: ' %} </p>
            </div>
            <div class="col-3 text-center ms-0 ps-2">
                <p class="cart-total-value mb-0 mt-3" style="color: #FD7014">{{ cart.total_cost|intcomma }} ₸</p>
                <p class="my-0" style="color:#FD7014">{{ service_percent }} %</p>
                <p style="color:#FD7014" class="cart-total-value-with-service my-0 fw-bold fs-5">
                    {{ cart.total_cost_with_service|intcomma }} ₸</p>
            </div>
            {% else %}
            <div class="col-8 text-end mx-0 px-0">
                <p class="mt-3 mb-0 fw-bold fs-5">{% translate 'Итого: ' %}</p>
            </div>
            <div class="col-4 text-center ms-0 ps-2">
                <p class="cart-total-value mb-0 mt-3 fw-bold fs-5" style="color: #FD7014">{{ cart.total_cost|intcomma }}
                    ₸</p>
            </div>
            {% endif %}
        </div>


        <div class="container text-center">
            <div class="d-flex justify-content-center py-4">
                {% if outside and phone %}
                <a class="text-center" target="_blank" href="https://wa.me/{{phone}}?text=
Здравствуйте, прошу принять заказ YAEM.KZ: %0a %0a
САМОВЫВОЗ: %0a %0a
{% for item in cart.cart_items.all %}
*{{ item.dish.name }}* - *{{ item.quantity }} шт.* %0a
{% if delivery_description %}
(_{{ item.dish.description }}_) %0a %0a
{% endif %}
{% endfor %}">
                    <button class="btn btn-success btn-rounded btn-animate mx-2">
                        Самовывоз
                        <i class="fas fa-shop fa-lg"></i>
                    </button>
                </a>
                {% endif %}
                {% if delivery and phone %}
                <a class="text-center" target="_blank" href="https://wa.me/{{phone}}?text=
Здравствуйте, прошу принять заказ YAEM.KZ: %0a %0a
ДОСТАВКА: %0a %0a
{% for item in cart.cart_items.all %}
*{{ item.dish.name }}* - *{{ item.quantity }} шт.* %0a
{% if delivery_description %}
(_{{ item.dish.description }}_) %0a %0a
{% endif %}
{% endfor %}">
                    <button class="btn btn-success btn-rounded btn-animate mx-2">
                        Доставка
                        <i class="fas fa-truck fa-lg"></i>
                    </button>
                </a>
                {% endif %}
            </div>
        </div>


        {% else %}
        <div class="container my-5" style="background: rgba(25, 25, 25, 0.5)">
            <h5 class="text-center py-5">{% translate 'Корзина пуста' %}</h5>
        </div>
    </div>

    {% endif %}
</section>
{% endblock content %}