YaEm/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
]

urlpatterns += i18n_patterns(
    path("", include("main.urls", namespace="main")),
    path("", include("partner.urls", namespace="partner")),
    path("", include("cart.urls", namespace="cart")),
    path("", include("banquets.urls", namespace="banquets")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', include('registration.urls', namespace='register')),
    prefix_default_language=False,
)

handler404 = "YaEm.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Yaem/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from Yaem.views import robots_txt_view, sitemap_xml_view

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
    # robots txt
    path('robots.txt', robots_txt_view, name='robots_txt'),
    # sitemap xml
    path('sitemap.xml', sitemap_xml_view, name='sitemap_xml'),
    # api v1
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    # Online documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/v1/ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]


urlpatterns += i18n_patterns(
    # menu
    path("", include("main.urls", namespace="main")),
    # partner
    path("", include("partner.urls", namespace="partner")),
    # cart
    path("", include("cart.urls", namespace="cart")),
    # banquets
    path("", include("banquets.urls", namespace="banquets")),
    # users
    path('user/', include('users.urls', namespace='users')),
    prefix_default_language=False,
)

handler404 = "Yaem.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

banquets/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from banquets.views import BanquetList, BanquetPage
from Yaem.settings import CACHES_LIFE_TIME

app_name = "banquets"

urlpatterns = [
    path(
        "banquets/",
        cache_page(CACHES_LIFE_TIME)(BanquetList.as_view()),
        name="banquet_list_page",
    ),
    path(
        "banquet/<str:url_name>",
        cache_page(CACHES_LIFE_TIME)(BanquetPage.as_view()),
        name="banquet_page",
    ),
]

banquets/models/banquet.py
from django.db import models

from banquets.models.utils.choices import HallNumber, ParkingType1, ParkingType2
from banquets.models.utils.images_upload import subhall_photo_upload_to


class Banquet(models.Model):
    banquet_card = models.ForeignKey(
        to="banquets.BanquetCard",
        on_delete=models.CASCADE,
        verbose_name="Карточка банкетного зала",
        null=True,
    )
    name = models.CharField(
        max_length=256, verbose_name="Название зала", default="Банкетный зал"
    )
    description = models.TextField(
        default="Добро пожаловать! Всегда рады видеть вас.",
        verbose_name="Описание зала",
        blank=True,
        null=True,
    )
    kitchen_types = models.ManyToManyField(
        to="banquets.KitchenType", verbose_name="Виды кухни"
    )
    features_name = models.ManyToManyField(
        to="banquets.FeaturesOfTheBanquetHall",
        verbose_name="Особенности банкетного зала",
    )
    parking_1 = models.CharField(
        blank=True,
        null=True,
        choices=ParkingType1.choices,
        max_length=256,
        verbose_name="Парковка: Охраняемая/Неохраняемая",
        default=ParkingType1.UNGUARDED_RU,
    )
    parking_2 = models.CharField(
        blank=True,
        null=True,
        choices=ParkingType2.choices,
        max_length=256,
        verbose_name="Парковка: Платная/Бесплатная",
        default=ParkingType2.FREE_RU,
    )

    memorials = models.CharField(
        max_length=256,
        verbose_name="Стоимость поминок(XXXX - XXXX)",
        blank=True,
        null=True,
    )
    sub_hall_capacity = models.CharField(
        max_length=256, verbose_name="Вместимость зала(XXX)"
    )
    sub_hall_price_for_person = models.CharField(
        max_length=256, verbose_name="Цена за человека(XXXX-XXXX)"
    )
    hall_no = models.IntegerField(
        choices=HallNumber.choices, default=HallNumber.HALL_1, verbose_name="№ Зала"
    )

    photo1 = models.ImageField(
        verbose_name="Фото 1", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo2 = models.ImageField(
        verbose_name="Фото 2", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo3 = models.ImageField(
        verbose_name="Фото 3", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo4 = models.ImageField(
        verbose_name="Фото 4", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo5 = models.ImageField(
        verbose_name="Фото 5", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo6 = models.ImageField(
        verbose_name="Фото 6", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo7 = models.ImageField(
        verbose_name="Фото 7", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo8 = models.ImageField(
        verbose_name="Фото 8", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo9 = models.ImageField(
        verbose_name="Фото 9", upload_to=subhall_photo_upload_to, blank=True, null=True
    )
    photo10 = models.ImageField(
        verbose_name="Фото 10", upload_to=subhall_photo_upload_to, blank=True, null=True
    )

    class Meta:
        verbose_name = "Банкетный зал"
        verbose_name_plural = "Банкетные залы"
        ordering = ("id",)

    def __str__(self):
        return self.name

banquets/models/banquet_card.py
from django.db import models

from banquets.models.utils.images_upload import banquet_logo_upload_to


class BanquetCard(models.Model):
    client = models.ForeignKey(
        to="main.Client",
        verbose_name="Зал заведения:",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    city = models.ForeignKey("main.City", models.CASCADE, verbose_name="Город")
    name = models.CharField(
        max_length=100, unique=True, verbose_name="Название банкетного зала"
    )
    url_name = models.CharField(
        max_length=30, verbose_name="/url=client url", unique=True
    )
    logo = models.ImageField(verbose_name="Лого", upload_to=banquet_logo_upload_to)
    photo1 = models.ImageField(
        verbose_name="Фото 1", upload_to=banquet_logo_upload_to, blank=True, null=True
    )
    photo2 = models.ImageField(
        verbose_name="Фото 2", upload_to=banquet_logo_upload_to, blank=True, null=True
    )
    photo3 = models.ImageField(
        verbose_name="Фото 3", upload_to=banquet_logo_upload_to, blank=True, null=True
    )
    capacity = models.PositiveIntegerField(verbose_name="Вместимость")
    min_capacity = models.PositiveIntegerField(
        verbose_name="Минимальная вместимость", blank=True, null=True
    )
    price_min = models.PositiveIntegerField(verbose_name="Мин. цена за человека")
    price_max = models.PositiveIntegerField(verbose_name="Макс. цена за человека")
    status = models.BooleanField(verbose_name="Активен")
    working_time = models.CharField(
        max_length=20, verbose_name="Рабочее время", blank=True, null=True
    )
    address = models.CharField(
        max_length=50, verbose_name="Адрес", blank=True, null=True, unique=True
    )
    whatsapp = models.CharField(
        max_length=50, verbose_name="WhatsApp", blank=True, null=True, unique=True
    )
    inst = models.CharField(
        max_length=100, verbose_name="Instagram", blank=True, null=True, unique=True
    )
    two_gis = models.CharField(
        max_length=150, verbose_name="2gis", blank=True, null=True, unique=True
    )
    phone = models.CharField(
        max_length=30, verbose_name="Телефон", blank=True, null=True, unique=True
    )
    z_index = models.IntegerField(
        verbose_name="Порядковый №", blank=True, null=True, default=11
    )

    class Meta:
        verbose_name = "Карточка зала"
        verbose_name_plural = "Карточки залов"
        ordering = ("-z_index",)

    def __str__(self):
        return self.name

banquets/models/features.py
from django.db import models


class FeaturesOfTheBanquetHall(models.Model):
    features_name = models.CharField(
        max_length=256, verbose_name="Особенности банкетного зала"
    )

    class Meta:
        verbose_name = "Особенность банкетного зала"
        verbose_name_plural = "Особенности банкетных залов"

    def __str__(self):
        return self.features_name

banquets/models/kitchen_type.py
from django.db import models


class KitchenType(models.Model):
    kitchen_type = models.CharField(max_length=256, verbose_name="Вид кухни")

    class Meta:
        verbose_name = "Вид кухни"
        verbose_name_plural = "Виды кухни"

    def __str__(self):
        return self.kitchen_type

banquets/views/banquet.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.views import View

from banquets.models import BanquetCard
from banquets.views import utils
from main.models import City


class BanquetList(View):
    template_name = "banquets/banquet_list.html"

    def get(self, request, *args, **kwargs):
        banquets = BanquetCard.objects.all().order_by("z_index")
        cities = City.objects.values_list("name", flat=True).distinct()
        capacity = request.GET.get("capacity")
        price_min_max = request.GET.get("price_min_max")
        city = request.GET.get("city")

        def apply_filter(queryset, field, values):
            q_objects = Q()
            for value in values:
                q_objects |= Q(**{field: value})
            return queryset.filter(q_objects)

        if capacity:
            banquets = banquets.filter(
                capacity__range=utils.capacity_ranges.get(capacity, (0, 9999))
            )

        if price_min_max:
            banquets = banquets.filter(
                price_min__range=utils.price_ranges.get(price_min_max, (0, 99999))
            )

        if city:
            for city_name, city_synonym_list in utils.city_synonyms.items():
                if city in city_synonym_list:
                    banquets = apply_filter(banquets, "city__name", city_synonym_list)

        context = {"banquets": banquets, "cities": cities}
        return render(request, self.template_name, context)

banquets/views/banquet_card.py
from django.views.generic import TemplateView

from banquets.models import BanquetCard


class BanquetPage(TemplateView):
    template_name = "banquets/banquet_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_name = self.kwargs["url_name"]
        banquet_card = BanquetCard.objects.get(url_name=url_name)
        subhall = banquet_card.banquet_set.all()
        context["banquet"] = banquet_card
        context["subhall"] = subhall
        return context

banquets/templates/banquets/banquet_list.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}


{% block title %} {% translate 'Я ЕМ | Банкетные залы' %} {% endblock title %}

{% block description %}
{% translate 'Банкетные залы в Темиртау, Караганде, Алмате, Астане для юбилея, свадьбы, корпоратива. Заказать банкет онлайн.' %}
{% endblock description %}

{% block content %}
<!--button up-->
<a id="scrollToTopButton" class="btn fs-1 mx-2 shadow btn-rounded"
   style="color: #fd7014; background: rgba(33, 37, 41, 0.5); position: fixed; bottom: 25px; left: 15px; display: none; z-index: 100"
   href="#header"
   data-mdb-ripple-color="#FD7014">
    <i class="fas fa-arrow-up-long"></i>
</a>
<!--button end-->


<!--COUNTER START-->

<!--COUNTER START-->
<section class="user-select-none" style="background: #212529">
    <div id="counter" class="indicator-list  container">
        <div class="row text-center fs-6 py-2 fw-bold" style="color: #fd7014">
            <div class="col-4 col-lg-4">
                <div id="counter-1" class="indicators-item"> <!--item-1-->
                    <div data-num="{{total_clients}}" class="indicators-title fs-5"></div>
                    <div class="lng-unit4 indicators-subtitle text-white"><i class="fas fa-store fa-xs">
                    </i> {% trans 'Заведений' %}
                    </div>
                </div>
            </div>
            <div class="col-4 col-lg-4">
                <div id="counter-2" class="indicators-item"> <!--item-2-->
                    <div data-num="{{total_banquets}}" class="indicators-title fs-5"></div>
                    <div class="lng-unit4 indicators-subtitle text-white"><i class="fas fa-bell-concierge fa-xs"></i> {% trans 'Залов' %}
                    </div>
                </div>
            </div>
            <div class="col-4 col-lg-4">
                <div id="counter-3" class="indicators-item"><!--item-3-->
                    <div data-num={{total_online}} class="indicators-title fs-5"></div>
                    <div class="lng-unit6 indicators-subtitle text-white">
                        <i class="fas fa-user fa-xs"></i> {% trans 'Онлайн' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--COUNTER END-->

<section class="skrollable pb-5"
         style="background-image: linear-gradient(0deg, rgba(25, 25, 25, 0.8), rgba(25, 25, 25, 0.9)), url({% static 'images/banquet/банкет-min.jpg' %});
    background-repeat: no-repeat; background-position: center center; background-attachment: fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover">
    <div class="container py-3">
        <h1 class="fw-bold text-center mb-5" style="color: #fd7014">{% translate 'Банкетные залы' %}
            <a target="_blank" data-aos="flip-up"
               href="https://wa.me/77015302812?text=Здравствуйте,%20какие%20условия%20размещения%20банкетного%20зала?"
               class="btn btn-rounded btn-info btn-sm btn-sm btn-animate py-auto">
                {% trans 'РАЗМЕСТИТЬ ЗАЛ' %}
            </a>
        </h1>
        <form action="" method="get">
            <div class="d-flex justify-content-center">
                <div class="d-inline-flex text-center">
                    <select class="form-select-sm" id="select_3" aria-label="Default select example"
                            name="city">
                        <option selected value="">{% trans 'Город' %}</option>
                        {% for city in cities %}
                        <option value="{{ city }}" {% if request.GET.city == city %}selected{% endif %}>{{ city }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="d-inline-flex text-center mx-2">
                    <select class="form-select-sm" id="select_2" aria-label="Default select example"
                            name="price_min_max">
                        <option selected value="">{% trans 'Цена за чел' %}</option>
                        <!--0 - 3000-->
                        <option value="3000" {% if request.GET.price_min_max == '3000' %}selected{% endif %}>{% trans 'до' %} 3 000</option>
                        <!--3000 - 5000-->
                        <option value="5000" {% if request.GET.price_min_max == '5000' %}selected{% endif %}>3 000 - 5 000</option>
                        <!--5000 - 10000-->
                        <option value="10000" {% if request.GET.price_min_max == '10000' %}selected{% endif %}>5 000 - 10 000</option>
                        <!--10000 - 15000-->
                        <option value="10001" {% if request.GET.price_min_max == '10001' %}selected{% endif %}>{% trans 'свыше' %} 10 000</option>
                    </select>
                </div>
                <div class="d-inline-flex text-center">
                    <select class="form-select-sm" id="select_1" aria-label="Default select example"
                            name="capacity">
                        <option selected value="">{% trans 'Вместимость' %}</option>
                        <!--0 - 100-->
                        <option value="100" {% if request.GET.capacity == '100' %}selected{% endif %}>{% trans 'до' %} 100</option>
                        <!--100 - 200-->
                        <option value="200" {% if request.GET.capacity == '200' %}selected{% endif %}>100-200</option>
                        <!--200 - 400-->
                        <option value="400" {% if request.GET.capacity == '400' %}selected{% endif %}>200-400</option>
                        <!--400 +-->
                        <option value="401" {% if request.GET.capacity == '401' %}selected{% endif %}>{% trans 'Свыше' %} 400</option>
                    </select>
                </div>
            </div>
            <div class="d-flex mx-auto mt-2 justify-content-center">
                <button data-aos="flip-up" class="btn btn-success btn-rounded btn-sm btn-animate" type="submit"><i
                        class="fas fa-magnifying-glass"></i> {% trans 'ПОИСК' %}
                </button>

            </div>
        </form>
    </div>


    <div class="container">

        <div class="row gy-5 mx-auto justify-content-center">
            <!--- цикл -->
            {% for banquet in banquets %}
            {% if banquet.status %}
            <div class="col-12 col-lg-6 text-center">
                <div class="card text-white" style="background: rgba(33, 37, 41, 0.5)">
                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>

                    <!-- Demo styles -->
                    <style>
                        html,
                        body {
                          position: relative;
                          height: 100%;
                        }

                        body {
                          background: #eee;
                          font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
                          font-size: 14px;
                          color: #000;
                          margin: 0;
                          padding: 0;
                        }

                        .swiper {
                          width: 90%;
                          height: 250px;
                          border-radius: 15px;
                        }

                        .swiper-slide {
                          text-align: center;
                          font-size: 18px;
                          background: rgba(33, 37, 41, 0);
                          display: flex;
                          justify-content: center;
                          align-items: center;
                        }

                        .swiper-slide img {
                          display: block;
                          max-width: 100%;
                          height: 100%;
                          object-fit: cover;
                          border-radius: 15px
                        }
                    </style>

                    <!-- Swiper -->
                    <a class="btn-animate" href="{% url 'banquets:banquet_page' url_name=banquet.url_name %}">
                        <div class="swiper mySwiper mt-1">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide"><img src="{{banquet.logo.url}}" loading="lazy" alt=""></div>
                                {% if banquet.photo1 %}
                                <div class="swiper-slide"><img src="{{ banquet.photo1.url }}" loading="lazy" alt="">
                                </div>
                                {% endif %}

                                {% if banquet.photo2 %}
                                <div class="swiper-slide"><img src="{{ banquet.photo2.url }}" loading="lazy" alt="">
                                </div>
                                {% endif %}

                                {% if banquet.photo3 %}
                                <div class="swiper-slide"><img src="{{ banquet.photo3.url }}" loading="lazy" alt="">
                                </div>
                                {% endif %}
                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </a>


                    <!-- Swiper JS -->
                    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

                    <!-- Initialize Swiper -->
                    <script>
                        var swiper = new Swiper(".mySwiper", {
                          slidesPerView: 1,
                          spaceBetween: 1,
                          loop: true,
                          lazy: true,
                          keyboard: {
                            enabled: false,
                          },
                          autoplay: {
                            delay: 6000,
                            disableOnInteraction: true,
                          },
                        });
                    </script>
                    <div class="card-body my-0 py-1">
                        <h5 class="card-title my-0">{% trans 'Банкетный зал' %}
                            <span style="color: #FD7014">{{ banquet.name }}</span></h5>
                        {% if banquet.address %}
                        <p class="card-title my-0 text-white-50">
                            {{ banquet.address }}
                        </p>
                        {% endif %}

                        <p class="card-text my-0 text-white-50">
                            {% translate 'Время работы' %}:
                            {% if banquet.working_time %}
                            {{ banquet.working_time }}
                            {% endif %}
                        </p>

                        <div class="d-flex justify-content-around my-2 ">
                            <p class="my-0 px-2 border rounded-pill"
                               style="color: #FD7014; --mdb-border-color: #FD7014">
                                <i class="fas fa-coins"></i> {{banquet.price_min}} ₸ - {{banquet.price_max}} ₸
                            </p>
                            <p class="my-0 px-2 border rounded-pill"
                               style="color: #FD7014; --mdb-border-color: #FD7014">
                                <i class="fas fa-user"></i>
                                {% if banquet.min_capacity %}
                                {{banquet.min_capacity}} -
                                {% endif %}
                                {{banquet.capacity}} {% trans 'мест' %}
                            </p>
                        </div>

                        <p class="my-0">{{ banquet.description }}</p>
                        <!--                        <a href="{% url 'banquets:banquet_page' url_name=banquet.url_name %}">-->
                        <!--                            <button data-aos="flip-up" class="btn btn-success btn-rounded px-4 my-2 btn-animate">-->
                        <!--                                {% translate 'Перейти' %}-->
                        <!--                            </button>-->
                        <!--                        </a>-->
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}