YaEm/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
]

urlpatterns += i18n_patterns(
    path("", include("main.urls", namespace="main")),
    path("", include("partner.urls", namespace="partner")),
    path("", include("cart.urls", namespace="cart")),
    path("", include("banquets.urls", namespace="banquets")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', include('registration.urls', namespace='register')),
    prefix_default_language=False,
)

handler404 = "YaEm.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Yaem/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from Yaem.views import robots_txt_view, sitemap_xml_view

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
    # robots txt
    path('robots.txt', robots_txt_view, name='robots_txt'),
    # sitemap xml
    path('sitemap.xml', sitemap_xml_view, name='sitemap_xml'),
    # api v1
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    # Online documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/v1/ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]


urlpatterns += i18n_patterns(
    # menu
    path("", include("main.urls", namespace="main")),
    # partner
    path("", include("partner.urls", namespace="partner")),
    # cart
    path("", include("cart.urls", namespace="cart")),
    # banquets
    path("", include("banquets.urls", namespace="banquets")),
    # users
    path('user/', include('users.urls', namespace='users')),
    prefix_default_language=False,
)

handler404 = "Yaem.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.LoginView.as_view(), name='signin'),
    path('signup/', views.RegistrationView.as_view(), name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

users/models/payment.py
from crum import get_current_user
from django.contrib.auth import get_user_model
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from main.models.utils.choices import PaymentStatuses


class Payment(models.Model):
    user = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.PROTECT,
        verbose_name='Пользователь',
        related_name='get_user_payments',
    )
    tarif_number = models.ForeignKey(
        "main.EstablishmentRates",
        on_delete=models.CASCADE,
        verbose_name="Тариф",
    )
    months = models.PositiveSmallIntegerField(verbose_name='Количество месяцев')
    phone = PhoneNumberField(verbose_name='Номер телефона')
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Время создания заявки'
    )
    status = models.CharField(
        choices=PaymentStatuses.choices, max_length=20, verbose_name='Статус'
    )

    class Meta:
        verbose_name = 'Заявки на оплату'
        verbose_name_plural = 'Заявки на оплату'
        ordering = ('created_at',)

    def save(self, *args, **kwargs):
        # Create relation with current user
        if not self.user_id:
            self.user = get_current_user()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.status

users/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from users.models.user_manager import CustomUserManager


class User(AbstractUser):
    username = models.CharField(blank=True, null=True, max_length=50)
    phone_number = PhoneNumberField(
        verbose_name='Номер телефона', unique=True, db_index=True
    )
    number_of_establishments = models.PositiveSmallIntegerField(default=2, verbose_name='Макс. Количество заведений')
    created_at = models.DateTimeField(
        auto_now_add=True, blank=True, verbose_name='Создан', null=True
    )

    USERNAME_FIELD = 'phone_number'

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('created_at',)

    def __str__(self):
        if self.is_superuser or self.is_staff:
            if self.first_name:
                return f'{self.phone_number}({self.first_name})'
            return f'{self.phone_number}'
        return f'{self.phone_number}'

users/models/user_manager.py
from django.contrib.auth.base_user import BaseUserManager


class CustomUserManager(BaseUserManager):
    def _create_user(
        self,
        phone_number=None,
        password=None,
        username=None,
        is_superuser=False,
        is_staff=False,
        **extra_fields
    ):
        if not phone_number:
            raise ValueError('Укажите номер телефона.')

        extra_fields.setdefault("is_superuser", is_superuser)
        extra_fields.setdefault("is_staff", is_staff)
        extra_fields.setdefault("is_active", True)

        user = self.model(phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(
        self, phone_number=None, password=None, username=None, **extra_fields
    ):
        return self._create_user(
            phone_number=phone_number,
            password=password,
            username=username,
            **extra_fields
        )

    def create_superuser(
        self, phone_number=None, password=None, username=None, **extra_fields
    ):
        return self._create_user(
            phone_number=phone_number,
            password=password,
            username=username,
            is_superuser=True,
            is_staff=True,
            **extra_fields
        )

users/forms/login.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField


class LoginForm(forms.Form):
    phone_number = PhoneNumberField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "class": "form-control",
                "placeholder": "Введите номер телефона",
            }
        )
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "form-control",
                "placeholder": "Введите пароль",
            }
        ),
    )

users/forms/registration.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Иван",
                "required": "true",
            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Иванов",
            }
        ),
        required=False,
    )
    phone_number = PhoneNumberField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "+77777777777",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "*youremail@example.com",
            }
        ),
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите ваш пароль",
                "required": "true",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Подтвердите ваш пароль",
                "required": "true",
            }
        )
    )

    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "phone_number",
            "email",
            "password1",
            "password2",
        )

users/views/login.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render, reverse
from django.views import View

from users.forms import LoginForm


class LoginView(View):
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('main:main_page')
        return render(
            request=request,
            template_name=self.template_name,
            context={'form': LoginForm()},
        )

    def post(self, request, *args, **kwargs):
        login_form = LoginForm(data=request.POST)

        if login_form.is_valid():
            phone_number = login_form.cleaned_data.get('phone_number')
            password = login_form.cleaned_data.get('password')
            user = authenticate(
                request=request, phone_number=phone_number, password=password
            )

            if user is not None:
                login(request, user)
                if user.first_name:
                    message = f'Добро пожаловать - {str(user.first_name).capitalize()}!'
                else:
                    message = 'Добро пожаловать!'
                messages.success(request=request, message=message)
            return redirect('main:delivery_list_page')

        return render(
            request=request,
            template_name=self.template_name,
            context={'form': login_form},
        )

users/views/logout.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View


@method_decorator(login_required, name="dispatch")
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        name = request.user.first_name
        if request.user.is_authenticated:
            logout(request)
            messages.warning(request, f"{name} - вы вышли из аккаунта")
            return redirect(reverse("main:delivery_list_page"))

users/views/registration.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render, reverse
from django.views import View

from users.forms import RegistrationForm


class RegistrationView(View):
    template_name = 'users/signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('main:main_page')
        return render(
            request=request,
            template_name=self.template_name,
            context={'form': RegistrationForm()},
        )

    def post(self, request, *args, **kwargs):
        registration_form = RegistrationForm(data=request.POST)

        if registration_form.is_valid():
            user = registration_form.save()
            login(request, user)

            message = f'{user.first_name} - вы успешно зарегистрировались!'
            messages.success(request=request, message=message)

            return redirect('main:delivery_list_page')

        return render(
            request=request,
            template_name=self.template_name,
            context={'form': registration_form},
        )

users/templates/users/base_registration.html
{% load static %}
{% load i18n %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>{% block title %}   {% endblock title %}</title>

    <!-- Favicons -->
    <link href="{% static 'images/base/favicon1-min.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png ' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!--    CSS ADMIN-->
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>
<body>


{% block content %}


{% endblock content %}
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

users/templates/users/login.html
{% extends "users/base_registration.html" %}
{% load static %}
{% load i18n %}
{% block title %}  YAEM | Вход {% endblock title %}

{% block content %}

<main>
    <div class="container">

        {# Сообщения!!! #}
        {% include "main/included/messages.html" %}

        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                        <div class="d-flex justify-content-center py-4">
                            <div class="logo d-flex align-items-center w-auto">
                                <img src="{% static 'images/base/favicon1-min.png' %}" alt="">
                                <span class="">YAEM.KZ</span>
                            </div>
                        </div><!-- End Logo -->

                        <div class="card mb-3">

                            <div class="card-body">

                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Войти в аккаунт</h5>
                                    <p class="text-center small">Введите номер телефона и пароль для входа</p>
                                </div>

                                <form method="POST" class="row g-3 needs-validation">
                                    {% csrf_token %}

                                    <div class="col-12">
                                        <label for="{{ form.phone_number.id_for_label }}" class="form-label">Номер телефона</label>
                                        <div class="input-group has-validation">
{#                                            <span class="input-group-text" id="inputGroupPrepend">@</span>#}
                                            {{ form.phone_number }}
                                            {{ form.phone_number.errors }}
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
                                        {{ form.password }}
                                        {{ form.password.errors }}
                                    </div>


{#                                    <div class="col-12">#}
{#                                        <div class="form-check">#}
{#                                            <input class="form-check-input" type="checkbox" name="remember" value="true"#}
{#                                                   id="rememberMe">#}
{#                                            <label class="form-check-label" for="rememberMe">Запомнить меня</label>#}
{#                                        </div>#}
{#                                    </div>#}

                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Войти</button>
                                    </div>


{#                                    <div class="text-center">#}
{#                                        <a class="mx-2" href="">#}
{#                                            <img src="{% static 'images/login/facebook.png' %}" alt=""#}
{#                                                 style="max-height: 40px">#}
{#                                        </a>#}
{#                                        <a class="mx-2" href="">#}
{#                                            <img src="{% static 'images/login/G__Logo.svg.png' %}" alt=""#}
{#                                                 style="max-height: 40px">#}
{#                                        </a>#}
{#                                        <a class="mx-2" href="">#}
{#                                            <img src="{% static 'images/login/mail_ru.png' %}" alt=""#}
{#                                                 style="max-height: 40px">#}
{#                                        </a>#}
{#                                    </div>#}
                                    <div class="col-12">
                                        <p class="small mb-0">Нет аккаунта? <a href="{% url 'users:signup' %}">
                                            Зарегистрируйтесь! </a></p>
                                    </div>
                                </form>

                            </div>
                        </div>

                        <div class="credits">
                            Designed by <a class="fw-bold" style="color: #FD7014">YAEM.KZ</a>
                        </div>

                    </div>
                </div>
            </div>

        </section>

    </div>
</main>

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
{% endblock content %}

users/templates/users/logout.html
{% load static %}
<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
        padding-top: 200px;
    }


    .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 350px;
    }



</style>
<body>

<div id="logoutModal" class="modal">
    <div class="modal-content text-black bg-light">
        <div class="modal-header my-0 py-0">
            <h5 class="modal-title">Выход из системы</h5>
            <button type="button" class="btn-close closeModalLogout" data-mdb-dismiss="modal"></button>
        </div>
        <!--        <span class="closeModalLogout">&times;</span>-->
        <p class="mt-3">Вы уверены, что хотите выйти? {{ request.user.full_name }}</p>
        <div class="d-flex justify-content-center">
            <a href="{% url 'users:logout' %}">
                <button class="btn btn-success mx-2 btn-animate">Да</button>
            </a>
            <button class="btn btn-danger closeModalLogout mx-2 btn-animate">Нет</button>
        </div>



    </div>
</div>

<script>
    var modal = document.getElementById("logoutModal");
    var closeButtons = document.getElementsByClassName("closeModalLogout");

    document.getElementById("logoutButton").onclick = function () {
        modal.style.display = "block";
    }

    for (var i = 0; i < closeButtons.length; i++) {
        closeButtons[i].onclick = function () {
            modal.style.display = "none";
        }
    }

    window.onclick = function (event) {
        if (event.target === modal) {
            modal.style.display = "none";
        }
    }
</script>

</body>

users/templates/users/signup.html
{% extends "users/base_registration.html" %}
{% load static %}
{% load i18n %}


{% block title %}  YAEM | Регистрация {% endblock title %}


{% block content %}
<main>
    <div class="container">

        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                        <div class="d-flex justify-content-center py-4">
                            <div class="logo d-flex align-items-center w-auto">
                                <img src="{% static 'images/base/favicon1-min.png' %}" alt="">
                                <span class="">YAEM.KZ</span>
                            </div>
                        </div><!-- End Logo -->

                        <div class="card mb-3">

                            <div class="card-body">

                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Создать аккаунт</h5>
                                    <p class="text-center small">Введите свои данные для создания аккаунта</p>
                                </div>

                                <form method="post" class="row g-3 needs-validation">
                                    {% csrf_token %}
                                    <div class="col-12">
                                        <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                        {{ form.first_name }}
                                        {{ form.first_name.errors }}
                                    </div>

                                    <div class="col-12">
                                        <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                        {{ form.last_name }}
                                        {{ form.last_name.errors }}
                                    </div>

                                    <div class="col-12">
                                        <label for="{{ form.phone_number.id_for_label }}" class="form-label">Номер телефона</label>
                                        {{ form.phone_number }}
                                        {{ form.phone_number.errors }}
                                    </div>

                                    <div class="col-12">
                                        <label for="{{ form.email.id_for_label }}" class="form-label">Адрес эл.почты</label>
                                        {{ form.email }}
                                        {{ form.email.errors }}
                                    </div>

                                    <div class="col-12">
                                        <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
                                        {{ form.password1 }}
                                        {{ form.password1.errors }}
                                    </div>

                                    <div class="col-12">
                                        <label for="{{ form.password2.id_for_label }}" class="form-label">Повторите пароль</label>
                                        {{ form.password2 }}
                                        {{ form.password2.errors }}
                                    </div>


                                    <div class="col-12">
                                        <div class="form-check">
                                            <input class="form-check-input" name="terms" type="checkbox" value=""
                                                   id="acceptTerms" required>
                                            <label class="form-check-label" for="acceptTerms">Я согласен с условиями <a
                                                    href="{% static 'Public_offer.pdf' %}" target="_blank">пользовательского соглашения</a></label>
                                            <div class="invalid-feedback">Требуется согласие</div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Создать аккаунт</button>
                                    </div>
                                    <div class="col-12">
                                        <p class="small mb-0">Уже есть аккаунт? <a href="{% url 'users:signin' %}">Войдите</a></p>
                                    </div>
                                </form>

                            </div>
                        </div>

                        <div class="credits">
                            Designed by <a class="fw-bold" href="#"
                                           style="color: #FD7014">YAEM</a>
                        </div>

                    </div>
                </div>
            </div>

        </section>

    </div>
</main><!-- End #main -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

{% endblock content %}