YaEm/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
]

urlpatterns += i18n_patterns(
    path("", include("main.urls", namespace="main")),
    path("", include("partner.urls", namespace="partner")),
    path("", include("cart.urls", namespace="cart")),
    path("", include("banquets.urls", namespace="banquets")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', include('registration.urls', namespace='register')),
    prefix_default_language=False,
)

handler404 = "YaEm.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Yaem/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from Yaem.views import robots_txt_view, sitemap_xml_view

urlpatterns = [
    # admin URLS
    path("admin/", admin.site.urls),
    # robots txt
    path('robots.txt', robots_txt_view, name='robots_txt'),
    # sitemap xml
    path('sitemap.xml', sitemap_xml_view, name='sitemap_xml'),
    # api v1
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    # Online documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/v1/ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]


urlpatterns += i18n_patterns(
    # menu
    path("", include("main.urls", namespace="main")),
    # partner
    path("", include("partner.urls", namespace="partner")),
    # cart
    path("", include("cart.urls", namespace="cart")),
    # banquets
    path("", include("banquets.urls", namespace="banquets")),
    # users
    path('user/', include('users.urls', namespace='users')),
    prefix_default_language=False,
)

handler404 = "Yaem.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

banquets/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from banquets.views import BanquetList, BanquetPage
from Yaem.settings import CACHES_LIFE_TIME

app_name = "banquets"

urlpatterns = [
    path(
        "banquets/",
        cache_page(CACHES_LIFE_TIME)(BanquetList.as_view()),
        name="banquet_list_page",
    ),
    path(
        "banquet/<str:url_name>",
        cache_page(CACHES_LIFE_TIME)(BanquetPage.as_view()),
        name="banquet_page",
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    # cart page
    path(
        '<slug:establishment_url_name>/cart', views.CartPage.as_view(), name='cart_page'
    ),
    # add to cart
    path('add/', views.add_to_cart, name='add'),
    # remove from cart
    path('remove/', views.remove_from_cart, name='remove'),
    # clear cart
    path('clear/', views.cart_remove, name='clear'),
]

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import DeliveryList, Main, Menu, set_language
from Yaem.settings import CACHES_LIFE_TIME

app_name = "main"

urlpatterns = [
    path(
        "<str:url_name>/menu",
        cache_page(CACHES_LIFE_TIME)(Menu.as_view()),
        name="menu_page",
    ),
    path("", cache_page(CACHES_LIFE_TIME)(Main.as_view()), name="main_page"),
    path("delivery/city/<slug:city_slug>/", DeliveryList.as_view(), name="city_filter"),
    path("set_language/<str:language>", set_language, name="set_language"),
    path(
        "delivery/",
        cache_page(CACHES_LIFE_TIME)(DeliveryList.as_view()),
        name="delivery_list_page",
    ),
]

cart/models/cart.py
import math

from django.contrib.auth import get_user_model
from django.contrib.auth.signals import user_logged_out
from django.contrib.sessions.models import Session
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from main.models import Dish


class Cart(models.Model):
    user = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        null=True,
    )
    items = models.ManyToManyField(
        to=Dish, through='CartItems', verbose_name='Блюда в корзине'
    )
    session_key = models.CharField(
        max_length=32, null=True, blank=True, verbose_name='Сессионный ключ'
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания корзины'
    )

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def total_cost(self):
        return sum(item.subtotal() for item in self.cart_items.all())

    def total_cost_with_service(self):
        return math.ceil(
            sum(item.subtotal_with_service() for item in self.cart_items.all())
        )

    def __str__(self):
        return f'{self.user}'


class CartItems(models.Model):
    cart = models.ForeignKey(
        to=Cart,
        on_delete=models.CASCADE,
        verbose_name='Корзина',
        related_name='cart_items',
    )
    dish = models.ForeignKey(to=Dish, on_delete=models.CASCADE, verbose_name='Блюдо')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')

    class Meta:
        verbose_name = 'Элемент корзины'
        verbose_name_plural = 'Элементы корзины'

    def subtotal(self):
        return self.dish.total_price() * self.quantity

    def subtotal_with_service(self):
        return self.dish.total_price_with_service() * self.quantity

    def __str__(self):
        return f'{self.dish} ({self.quantity}) в корзине'

cart/views/add_to_cart.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from cart.models import Cart, CartItems
from main.models import Dish


@csrf_exempt
def add_to_cart(request):
    # Получаем id блюда из POST-запроса
    dish_id = request.POST.get('dish_id')
    # Получаем объект блюда по его id или возвращаем ошибку 404, если блюдо не найдено
    dish = get_object_or_404(Dish, pk=dish_id)
    # Получаем пользователя, отправившего запрос
    user = request.user

    # Если пользователь аутентифицирован
    if request.user.is_authenticated:
        # Получаем или создаем корзину пользователя
        cart, created = Cart.objects.get_or_create(user=user)
    else:
        # Если пользователь не аутентифицирован, используем его сессионный ключ для создания или получения корзины
        session_key = request.session.session_key

        # Если сессионного ключа нет, сохраняем его
        if not session_key:
            request.session.save()
            session_key = request.session.session_key

        # Получаем или создаем корзину для анонимного пользователя
        cart, created = Cart.objects.get_or_create(
            session_key=session_key, user_id=None
        )

    # Получаем или создаем элемент корзины для данного блюда в корзине пользователя
    cart_item, item_created = CartItems.objects.get_or_create(cart=cart, dish=dish)

    # Увеличиваем количество выбранного блюда на 1 или устанавливаем его равным 1, если элемент корзины был только что создан
    if item_created:
        cart_item.quantity = 1
    else:
        cart_item.quantity += 1

    # Получаем количество выбранного блюда в корзине
    quantity_in_cart = cart_item.quantity
    cart_item.save()

    # Получаем промежуточную стоимость выбранного блюда
    subtotal = cart_item.subtotal()
    # Получаем общую стоимость всех блюд в корзине
    total = cart.total_cost()
    total_with_service = cart.total_cost_with_service()

    # Возвращаем JSON-ответ с информацией о добавленном блюде в корзину
    return JsonResponse(
        {
            'success': True,
            'subtotal': subtotal,
            'total': total,
            'total_with_service': total_with_service,
            'quantity': quantity_in_cart,
        }
    )

cart/views/cart_page.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView

from main.models import Client


class CartPage(TemplateView):
    template_name = 'cart/cart.html'

    def get(self, request, establishment_url_name=None, *args, **kwargs):
        client = get_object_or_404(Client, url_name=establishment_url_name)
        return render(
            request=request,
            template_name=self.template_name,
            context={
                'establishment_url': establishment_url_name,
                'service_percent': client.service,
                'delivery': client.delivery,
                'outside': client.outside,
                'phone': client.phone,
                'delivery_description': client.delivery_description,
            },
        )

cart/views/clear_cart.py
from django.contrib import messages
from django.shortcuts import redirect

from cart.models import Cart, CartItems


def cart_remove(request):
    # Если пользователь аутентифицирован
    if request.user.is_authenticated:
        # Получаем корзину пользователя
        user_cart = Cart.objects.filter(user=request.user).first()
        # Если у пользователя есть корзина
        if user_cart:
            # Удаляем все элементы корзины
            user_cart.cart_items.all().delete()
    else:
        # Получаем сессионный ключ пользователя
        session_key = request.session.session_key
        # Если сессионный ключ существует
        if session_key:
            # Получаем корзину анонимного пользователя
            user_cart = Cart.objects.filter(session_key=session_key).first()
            # Если у пользователя есть корзина
            if user_cart:
                # Удаляем все элементы корзины
                user_cart.cart_items.all().delete()

    messages.warning(request, message='Корзина очищена.')
    # Перенаправляем пользователя на предыдущую страницу
    return redirect(request.META.get('HTTP_REFERER'))

cart/views/remove_from_cart.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from cart.models import Cart, CartItems


@csrf_exempt
def remove_from_cart(request):
    # Получаем id блюда из POST-запроса
    dish_id = request.POST.get('dish_id')

    # Если пользователь аутентифицирован
    if request.user.is_authenticated:
        # Получаем корзину пользователя
        cart = Cart.objects.filter(user=request.user).first()
    else:
        # Получаем сессионный ключ пользователя
        session_key = request.session.session_key

        # Если сессионного ключа нет, сохраняем его
        if not session_key:
            request.session.save()
            session_key = request.session.session_key

        # Получаем корзину анонимного пользователя
        cart = Cart.objects.filter(session_key=session_key).first()

    # Если корзина пользователя существует
    if cart:
        # Получаем элемент корзины для данного блюда в корзине пользователя
        cart_item = get_object_or_404(CartItems, cart=cart, dish_id=dish_id)

        # Если количество выбранного блюда больше 1, уменьшаем его на 1
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            quantity_in_cart = cart_item.quantity
            cart_item.save()
        # Иначе удаляем элемент корзины
        else:
            cart_item.delete()
            quantity_in_cart = 0

        # Получаем промежуточную стоимость выбранного блюда (если элемент корзины существует) или устанавливаем равной 0
        subtotal = cart_item.subtotal() if cart_item else 0
        # Получаем общую стоимость всех блюд в корзине (если корзина существует) или устанавливаем равной 0
        total = cart.total_cost() if cart else 0
        total_with_service = cart.total_cost_with_service()

        # Возвращаем JSON-ответ с информацией о удалении блюда из корзины
        return JsonResponse(
            {
                'success': True,
                'subtotal': subtotal,
                'total': total,
                'total_with_service': total_with_service,
                'quantity': quantity_in_cart,
            }
        )

main/views/delivery_list.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from main.models import City, Client


class DeliveryList(TemplateView):
    template_name = "main/delivery_list.html"

    def get_context_data(self, city_slug=None, **kwargs):
        context = super().get_context_data(**kwargs)
        city_selected = None
        # query = self.request.GET.get("q")
        clients = Client.objects.filter(status=True, delivery=True)

        if city_slug:
            city_selected = get_object_or_404(City, slug=city_slug)
            clients = Client.objects.filter(
                city=city_selected, status=True, delivery=True
            )
        # elif query:
        #     clients = Client.objects.filter(name__icontains=query)
        context["clients"] = clients
        context["cities"] = sorted(
            {
                client.city
                for client in Client.objects.filter(status=True, delivery=True)
                if client.city
            },
            key=lambda city: city.z_index,
        )
        context["city_selected"] = city_selected
        return context

main/views/language.py
from urllib.parse import urlparse

from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls.base import resolve, reverse
from django.urls.exceptions import Resolver404
from django.utils import translation

from banquets.models import BanquetCard
from main.models import Category, City, Client, Dish, Food_type


def set_language(request, language):
    for lang, _ in settings.LANGUAGES:
        translation.activate(lang)
        try:
            view = resolve(urlparse(request.META.get("HTTP_REFERER")).path)
        except Resolver404:
            view = None
        if view:
            break
    if view:
        translation.activate(language)
        next_url = reverse(
            f"{view.namespace}:{view.url_name}", args=view.args, kwargs=view.kwargs
        )
        response = HttpResponseRedirect(next_url)
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
    else:
        response = HttpResponseRedirect("/")
    return response

main/views/menu.py
from datetime import date, datetime

from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from banquets.models import BanquetCard
from cart.models import Cart
from main.models import Category, Client, Dish, Food_type


class Menu(TemplateView):
    template_name = "main/menu.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_name = self.kwargs["url_name"]
        # get establishment info
        client = get_object_or_404(Client, url_name=url_name)
        categories = client.get_categories.prefetch_related(
            'get_subcategories__get_dishes'
        ).all()

        food_types_without_dishes = []
        food_types = []
        dishes = []
        for category in categories:
            subcategories = category.get_subcategories.all()
            food_types.extend(subcategories)
            for food_type in subcategories:
                dish = food_type.get_dishes.filter(stop=False)
                dishes.extend(dish)

        for food_type in food_types:
            if food_type.get_dishes.count() > 0:
                food_types_without_dishes.append(food_type)

        client_has_banquet = BanquetCard.objects.filter(client=client).exists()
        # dish quantity
        user_cart = None
        if self.request.user.is_authenticated:
            user_cart = Cart.objects.filter(user=self.request.user).first()
        else:
            user_cart = Cart.objects.filter(
                session_key=self.request.session.session_key
            ).first()

        cart_items = {}
        if user_cart:
            for cart_item in user_cart.cart_items.all():
                cart_items[cart_item.dish.id] = cart_item.quantity
        client_date = client.paid_at
        today_date = datetime.now().date()

        context['client_date'] = client_date
        context['today_date'] = today_date
        context["dishes"] = dishes
        context['cart_items'] = cart_items
        context["food_type"] = food_types_without_dishes
        context["categories"] = categories
        context["client"] = client
        context["client_has_banquet"] = client_has_banquet
        print(context)

        return context

partner/views/partner.py
from django.views.generic import RedirectView


class Partner(RedirectView):
    permanent = True
    url = 'https://online-menu.org/'

main/templates/main/banquet_list.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}


{% block title %} {% translate 'Я ЕМ | Доставка еды напрямую от заведения' %} {% endblock title %}

{% block content %}

<!--button up-->
<a id="scrollToTopButton" class="btn fs-1 mx-2 shadow btn-rounded"
   style="color: #fd7014; background: rgba(33, 37, 41, 0.5); position: fixed; bottom: 25px; left: 15px; display: none; z-index: 100"
   href="#header"
   data-mdb-ripple-color="#FD7014">
    <i class="fas fa-arrow-up-long"></i>
</a>
<!--button end-->

<!--COUNTER START-->
<section class="user-select-none" style="background: #212529">
    <div id="counter" class="indicator-list  container">
        <div class="row text-center fs-4 py-2 fw-bold" style="color: #fd7014">
            <div class="col-6 col-lg-4">
                <div class="indicators-item"> <!--item-1-->
                    <div data-num="{{total_clients}}" class="indicators-title"></div>
                    <div class="lng-unit4 indicators-subtitle text-white"><i class="fas fa-store fa-xs">
                    </i> {% trans 'Заведений' %}
                    </div>
                </div>
            </div>
            <div class="col-6 col-lg-4">
                <div class="indicators-item"> <!--item-1-->
                    <div data-num={{total_dishes}} class="indicators-title"></div>
                    <div class="lng-unit4 indicators-subtitle text-white"><i class="fas fa-utensils fa-xs">

                    </i> {% trans 'Блюд' %}
                    </div>
                </div>
            </div>
            <div class="col-6 col-lg-4">
                <div class="indicators-item"><!--item-3-->
                    <div data-num={{total_orders}} class="indicators-title"></div>
                    <div class="lng-unit6 indicators-subtitle text-white">
                        <i class="fas fa-user fa-xs"></i> {% trans 'Онлайн' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--COUNTER END-->

<main class="user-select-none">
    <section class="skrollable pb-5"
             style="background-image: linear-gradient(0deg, rgba(51, 51, 51, 0.8), rgba(51, 51, 51, 0.9)), url({% static 'images/банкет.jpg' %});
    background-attachment: fixed; background-size: cover;">
        <div class="container">
            <h1 class="pt-4 fw-bold text-center" style="color: #fd7014">{% translate 'Банкетные залы в' %} {{city_selected}}</h1>

            <div class="row gy-3">
                <div class="col-12 text-center mx-auto">

                    <!--   CITY FOR LOOP     -->
                    <div class="btn-group-sm" role="group">
                        <a href="{% url 'main:main_page' %}"
                           {% if city_selected is None %}
                           class="btn btn-warning btn-animate"
                           {% else %}
                           class="btn btn-success btn-animate"
                           {% endif %}>{% translate 'Все' %}
                        </a>

                        {% for city in cities %}
                        <a href="{% url 'main:city_filter' city.slug %}"
                           {% if city.pk == city_selected.pk %}
                           class="btn btn-warning btn-animate"
                           {% else %}
                           class="btn btn-success btn-animate"
                           {% endif %}>{{ city }}
                        </a>
                        {% endfor %}
                    </div>
                </div>
                <!--   END CITY FOR LOOP     -->

                <!--  SEARCH FIELD -->
<!--                <div class="col-8 col-md-4 text-center mx-auto">-->
<!--                    <form method="get" class="text-center">-->
<!--                        <div class="input-group">-->
<!--                            <div class="form-outline form-white">-->
<!--                                <input id="search-input" name="q" class="form-control"/>-->
<!--                                <label class="form-label" for="search-input">Поиск заведения</label>-->
<!--                            </div>-->
<!--                            <button type="submit" class="btn btn-warning btn-animate" data-mdb-html="true"-->
<!--                                    data-mdb-toggle="tooltip" title="Hi! I'm tooltip">-->
<!--                                <i class="fas fa-search"></i>-->
<!--                            </button>-->
<!--                        </div>-->
<!--                    </form>-->
<!--                </div>-->

            </div>

            <!--      TEST LOGIN/REGISTER BUTTONS      -->
<!--            <a href="{% url 'accounts:signup' %}">Регистрация</a>-->
<!--            <a href="{% url 'accounts:login' %}">Войти</a>-->
<!--            {% if user.is_authenticated %}-->
<!--            <a href="{% url 'accounts:logout' %}">Выйти</a>-->
<!--            <a href="{% url 'accounts:change_password' %}">Сменить пароль</a>-->
<!--            <a href="{% url 'accounts:reset_password' %}">Сбросить пароль</a>-->
<!--            {% endif %}-->


            <!-- END SEARCH FIELD -->
        </div>

        <div class="container">
            <div class="row my-3 gy-3 mx-auto justify-content-center">

                <!--- цикл -->
                {% for client in clients %}
                {% if client.status and client.tarif_number.name == "СЕРЕБРО" or client.tarif_number.name == "ЗОЛОТО" %}
                <div class="col-12 col-md-6 col-lg-4 text-center">
                    <div class="card text-white" style="background: rgba(33, 37, 41, 0.5)">
                        <img data-aos="zoom-out-right" src="{{client.logo.url}}"
                             class="card-img-top mx-auto mt-2 mb-0 rounded"
                             alt="logo image"
                             style="max-width: 225px; max-height: 225px"
                        draggable="false">

                        <div class="card-body my-0 py-1">
                            <h4 data-aos="zoom-out-right" class="card-title my-0">{{ client.name }}</h4>
                            <p data-aos="zoom-out-right" class="card-text my-0 text-white-50">{% translate 'Время работы' %}:
                                {{ client.working_time }}</p>
                            <p data-aos="zoom-out-right" class="my-0">{{ client.description }}</p>
                            <div class="row my-0">
                                <div data-aos="zoom-out-right" class="col-6 my-0">
                                    <p class="text my-0"> {% translate 'Самовывоз' %}
                                        {% if client.outside %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                                             fill="currentColor"
                                             class="bi bi-check bg-success" viewBox="0 0 16 16"
                                             style="border-radius: 25px;">
                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                        </svg>
                                        {% else %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                                             class="bi bi-x bg-danger" viewBox="0 0 16 16"
                                             style="border-radius: 25px;">
                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                    </p>
                                    {% endif %}
                                </div>
                                <div data-aos="fade-up" class="col-6 my-0">
                                    <p class="my-0">{% translate 'Доставка' %}
                                        {% if client.delivery %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                                             fill="currentColor"
                                             class="bi bi-check bg-success" viewBox="0 0 16 16"
                                             style="border-radius: 25px;"> viewBox="0 0 16 16">
                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                        </svg>
                                        {% else %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                                             class="bi bi-x bg-danger" viewBox="0 0 16 16"
                                             style="border-radius: 25px;">
                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                            <a href="{% url 'main:menu_page' url_name=client.url_name %}">
                                <button data-aos="fade-up" class="btn btn-success btn-rounded px-4 my-2 btn-animate">{% translate 'Перейти' %}
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>

</main>

{% endblock content %}